site_name: Grid-Adventure1 Documentation

theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - Home: index.md
  - Player Guide:
      - Introduction: player-guide/introduction.md
      - Entities: player-guide/entities.md
      - Objectives: player-guide/objectives.md
      - Movements: player-guide/movements.md
  - Agent Documentation:
        - Grid Adventure Enviroment: agent-doc/grid_adventure_enviroment.md 
        - Game Representation: agent-doc/game_representation.md
        - Observation Representation: agent-doc/observation.md
        - Entity Classes: agent-doc/entities.md
        - Action Classes: agent-doc/action.md
        - Agent Class: agent-doc/agent.md
        - State Representation: agent-doc/state.md

